# Generated by Django 5.0.6 on 2024-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Not Neccessory', null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
