# Generated by Django 4.2.15 on 2024-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0010_depart_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_testing_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
