# Generated by Django 4.2.15 on 2024-09-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0019_internationaltraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
