# Generated by Django 4.2.15 on 2024-09-19 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0021_sdt_vayumitra_serial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternationalTraining',
            new_name='SDT_InternationalTraining',
        ),
    ]
