# Generated by Django 4.2.15 on 2024-09-19 11:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0030_sdt_webinar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_Short_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
