# Generated by Django 4.2.15 on 2024-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0032_wra_sale_publication_wra_srra_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='total_amount',
            field=models.CharField(max_length=250),
        ),
    ]
