# Generated by Django 4.2.15 on 2024-09-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0033_alter_wra_sale_publication_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='charge',
            field=models.CharField(max_length=250),
        ),
    ]
