# Generated by Django 4.2.15 on 2024-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0034_alter_wra_sale_publication_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wra_sale_publication',
            old_name='total_amount',
            new_name='total_amount1',
        ),
        migrations.AddField(
            model_name='wra_sale_publication',
            name='total_amount2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
