# Generated by Django 4.2.15 on 2024-09-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0035_rename_total_amount_wra_sale_publication_total_amount1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Numeric_Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('domain', models.CharField(max_length=250)),
                ('number_station', models.IntegerField()),
                ('error_of_wind_speed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
