# Generated by Django 4.2.15 on 2024-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0036_wra_numeric_wind'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Micro_Servey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('state', models.CharField(max_length=250)),
                ('stations', models.IntegerField()),
            ],
        ),
    ]
