# Generated by Django 4.2.15 on 2024-09-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0037_wra_micro_servey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Estimated_Potential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('state_ut', models.CharField(max_length=250)),
                ('potential_50m', models.IntegerField()),
                ('potential_80m', models.IntegerField()),
            ],
        ),
    ]
