# Generated by Django 4.2.15 on 2024-09-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0038_wra_estimated_potential'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Srra_Station_phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('phase_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WRA_Srra_Phase_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('comission', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('elavation', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.wra_srra_station_phases')),
            ],
        ),
    ]
