# Generated by Django 4.2.15 on 2024-09-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0039_wra_srra_station_phases_wra_srra_phase_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdt_customize_training',
            old_name='url',
            new_name='link',
        ),
    ]
