# Generated by Django 4.2.15 on 2024-09-23 11:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0042_alter_sdt_national_title_alter_sdt_national_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_national',
            name='url',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
