# Generated by Django 4.2.15 on 2024-09-23 12:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0044_sdt_national_page_alter_sdt_national_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_national',
            name='page',
        ),
        migrations.CreateModel(
            name='SDT_National_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_national')),
            ],
        ),
    ]
