# Generated by Django 4.2.15 on 2024-09-23 12:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0047_alter_sdt_national_page_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_national_page',
            name='data',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
