# Generated by Django 4.2.15 on 2024-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0050_sdt_internationaltraining_eitec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_internationaltraining',
            name='url',
        ),
    ]
