# Generated by Django 4.2.15 on 2024-09-24 09:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0051_remove_sdt_internationaltraining_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_Customize_Training_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_customize_training')),
            ],
        ),
    ]
