# Generated by Django 4.2.15 on 2024-09-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0052_sdt_customize_training_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_customize_training',
            name='link',
        ),
    ]
