# Generated by Django 4.2.15 on 2024-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0054_sdt_internationaltraining_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='comission',
            field=models.DateField(default='2023-09-25') , # Replace with an appropriate date
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='district',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='elavation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='station_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wra_srra_station_phases',
            name='station_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        
    ]
