# Generated by Django 4.2.15 on 2024-09-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0055_wra_srra_station_phases_comission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wra_srra_station_phases',
            old_name='comission',
            new_name='comission_date',
        ),
    ]
