# Generated by Django 4.2.15 on 2024-09-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0056_rename_comission_wra_srra_station_phases_comission_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WRA_Srra_Station_phases',
            new_name='WRA_Srra_Station_phase',
        ),
    ]
