# Generated by Django 4.2.15 on 2024-09-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0057_rename_wra_srra_station_phases_wra_srra_station_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WRA_Srra_Station_phase',
        ),
    ]
