# Generated by Django 4.2.15 on 2024-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0058_delete_wra_srra_station_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Srra_Station_phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('phase_type', models.CharField(max_length=250)),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('comission_date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('elavation', models.IntegerField()),
            ],
        ),
    ]
