# Generated by Django 4.2.15 on 2024-09-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0059_wra_srra_station_phase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WRA_Srra_Station_phase',
            new_name='WRA_Srra_Station_phases',
        ),
        migrations.DeleteModel(
            name='WRA_Srra_Phase_num',
        ),
    ]
