# Generated by Django 4.2.15 on 2024-09-25 08:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0061_wra_srra_station_ams_wra_srra_station_anert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_Training_calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_To', models.DateField()),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SDT_Training_Sub_calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_training_calender')),
            ],
        ),
    ]
