# Generated by Django 4.2.15 on 2024-09-25 11:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0063_sdt_training_calender_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_Eitc_Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('project_title', models.CharField(max_length=200)),
                ('no_of_country', models.IntegerField()),
                ('no_of_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SDT_Eitc_Sub_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_eitc_trainings')),
            ],
        ),
    ]
