# Generated by Django 5.0.6 on 2024-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0066_alter_sdt_library_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='charge',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='remarks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='total_amount2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
