# Generated by Django 4.2.15 on 2024-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0071_remove_sdt_vayumitra_docs_sdt_vayumitra_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_vayumitra',
            name='docs',
            field=models.FileField(blank=True, upload_to='annual-reports/'),
        ),
        migrations.AddField(
            model_name='sdt_vayumitra',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='title',
            field=models.CharField(max_length=205),
        ),
        migrations.DeleteModel(
            name='SDT_Vayumitra_sub',
        ),
    ]
