# Generated by Django 4.2.15 on 2024-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0073_sdt_vayumitra_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='url',
            field=models.URLField(blank=True, default='docs'),
        ),
    ]
