# Generated by Django 5.0.6 on 2024-09-27 11:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0076_remove_sdt_vayumitra_title_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='remarks',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
