# Generated by Django 4.2.15 on 2024-09-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0079_alter_wra_sale_publication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_library',
            name='subcription_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
