# Generated by Django 4.2.15 on 2024-10-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0080_alter_sdt_library_subcription_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedImage',
        ),
    ]
