# Generated by Django 4.2.15 on 2024-10-24 09:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0082_remove_sdt_short_term_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_Ireda_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('title', models.CharField(max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='SDT_Ireda_Sub_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_ireda_news')),
            ],
        ),
    ]
