# Generated by Django 4.2.15 on 2024-10-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0085_sdt_vayumitra_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdt_vayumitra',
            old_name='url',
            new_name='urls',
        ),
    ]
