# Generated by Django 4.2.15 on 2024-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0089_alter_sdt_workshop_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_globalwindday',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
