# Generated by Django 5.0.6 on 2024-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen_Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Citizen Charter')),
                ('document_File', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('document_File', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
