# Generated by Django 5.0.6 on 2024-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0007_events_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='document_File',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
