# Generated by Django 5.0.6 on 2024-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0008_alter_events_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, upload_to='static/'),
        ),
    ]
