# Generated by Django 4.2.15 on 2024-09-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0011_remove_album_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subalbums/')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SubGallery',
        ),
        migrations.AddField(
            model_name='subalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media_Section.album'),
        ),
    ]
