# Generated by Django 4.2.15 on 2024-10-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0013_delete_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='SubAlbum',
            new_name='SubGallery',
        ),
    ]
