# Generated by Django 4.2.15 on 2024-10-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0014_rename_album_gallery_rename_subalbum_subgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Think_Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Think_Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subalbums/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media_Section.think_tank')),
            ],
        ),
    ]
