# Generated by Django 4.2.15 on 2024-10-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0015_think_tank_sub_think_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
