# Generated by Django 5.0.6 on 2024-06-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiffBetweenFosilFuelWind',
            new_name='ComparisonBetweenFosilFuelAndWind',
        ),
    ]
