# Generated by Django 5.0.6 on 2024-06-20 11:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0002_rename_diffbetweenfosilfuelwind_comparisonbetweenfosilfuelandwind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='FAQs',
            new_name='Faq',
        ),
        migrations.AddField(
            model_name='faqs',
            name='preambel',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
