# Generated by Django 4.2.15 on 2024-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0005_relatedlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('upto_31_03_2002', models.IntegerField()),
                ('_2002_03', models.IntegerField()),
                ('_2003_04', models.IntegerField()),
                ('_2004_05', models.IntegerField()),
                ('_2005_06', models.IntegerField()),
                ('_2006_07', models.IntegerField()),
                ('_2007_08', models.IntegerField()),
                ('_2008_09', models.IntegerField()),
                ('_2009_10', models.IntegerField()),
                ('_2010_11', models.IntegerField()),
                ('_2011_12', models.IntegerField()),
                ('_2012_13', models.IntegerField()),
                ('_2013_14', models.IntegerField()),
                ('_2014_15', models.IntegerField()),
                ('_2015_16', models.IntegerField()),
                ('_2016_17', models.IntegerField()),
                ('_2017_18', models.IntegerField()),
                ('_2018_19', models.IntegerField()),
                ('_2019_20', models.IntegerField()),
                ('_2020_21', models.IntegerField()),
                ('_2021_22', models.IntegerField()),
            ],
        ),
    ]
