# Generated by Django 4.2.15 on 2024-08-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0009_rename__2002_03_weg_installation_details_india_y_2002_03'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2003_04',
            new_name='year_2002_03',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2004_05',
            new_name='year_2003_04',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2005_06',
            new_name='year_2004_05',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2006_07',
            new_name='year_2005_06',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2007_08',
            new_name='year_2006_07',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2008_09',
            new_name='year_2007_08',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2009_10',
            new_name='year_2008_09',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2010_11',
            new_name='year_2009_10',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2011_12',
            new_name='year_2010_11',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2012_13',
            new_name='year_2011_12',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2013_14',
            new_name='year_2012_13',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2014_15',
            new_name='year_2013_14',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2015_16',
            new_name='year_2014_15',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2016_17',
            new_name='year_2015_16',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2017_18',
            new_name='year_2016_17',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2018_19',
            new_name='year_2017_18',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2019_20',
            new_name='year_2018_19',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2020_21',
            new_name='year_2019_20',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2021_22',
            new_name='year_2020_21',
        ),
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='y_2002_03',
            new_name='year_2021_22',
        ),
    ]
