# Generated by Django 4.2.15 on 2024-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0012_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
