# Generated by Django 4.2.15 on 2024-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0015_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
