# Generated by Django 4.2.15 on 2024-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0018_delete_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='media/')),
            ],
        ),
    ]
