# Generated by Django 4.2.15 on 2024-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0031_alter_faqs_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisedguidelinesforproject',
            name='description',
        ),
        migrations.AddField(
            model_name='revisedguidelinesforproject',
            name='documents',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revisedguidelinesforproject',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
