# Generated by Django 4.2.15 on 2024-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0032_remove_revisedguidelinesforproject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisedguidelinesforproject',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revisedguidelinesforproject',
            name='documents',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
