# Generated by Django 4.2.15 on 2024-10-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0033_alter_revisedguidelinesforproject_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisedguidelinesforproject',
            name='date',
            field=models.DateField(),
        ),
    ]
