# Generated by Django 5.0.6 on 2024-06-17 15:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', tinymce.models.HTMLField()),
                ('image_1', models.ImageField(default=None, null=True, upload_to='images/')),
                ('image_2', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
