# Generated by Django 5.0.6 on 2024-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
