# Generated by Django 5.0.6 on 2024-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0002_alter_media_image_1_alter_media_image_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Award',
        ),
    ]
