# Generated by Django 4.2.15 on 2024-09-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Section', '0012_subalbum_alter_album_cover_image_alter_album_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
