# Generated by Django 5.0.6 on 2024-06-21 10:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackAndAddress', tinymce.models.HTMLField()),
                ('testingAndResearchStation', tinymce.models.HTMLField()),
            ],
        ),
    ]
