# Generated by Django 5.0.6 on 2024-06-21 10:48

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='feedbackAndAddress',
            new_name='feedback_and_Address',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='testingAndResearchStation',
            new_name='testing_and_Research_Station',
        ),
    ]
