# Generated by Django 5.0.6 on 2024-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Right_To_Information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='righttoinformation',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
