# Generated by Django 4.2.15 on 2024-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Right_To_Information', '0002_alter_righttoinformation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.RemoveField(
            model_name='righttoinformation',
            name='title',
        ),
    ]
