# Generated by Django 4.2.15 on 2024-10-22 10:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Right_To_Information', '0004_alter_information_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='url',
        ),
        migrations.CreateModel(
            name='subInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Right_To_Information.information')),
            ],
        ),
    ]
