# Generated by Django 5.0.6 on 2024-06-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutNiwe',
            new_name='AboutUs',
        ),
    ]
