# Generated by Django 5.0.6 on 2024-06-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0003_background_charter_director_general_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charter',
            old_name='Mission',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='organizational_chart',
            old_name='structureImage',
            new_name='image',
        ),
    ]
