# Generated by Django 5.0.6 on 2024-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0008_alter_director_general_office_staff_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DIRECTOR_GENERAL_MESSAGE',
            new_name='DirectorGeneralMessage',
        ),
        migrations.RenameModel(
            old_name='Organizational_Chart',
            new_name='OrganizationalChart',
        ),
        migrations.RenameModel(
            old_name='Quality_Policy',
            new_name='QualityPolicy',
        ),
        migrations.DeleteModel(
            name='Director_General_Office_Staff',
        ),
    ]
