# Generated by Django 5.0.6 on 2024-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Section', '0004_remove_offshorewinddevelopstaff_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorGeneralOfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, default='Not Avaliable', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
