# Generated by Django 4.2.15 on 2024-09-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Section', '0007_staffphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffphoto',
            old_name='profile',
            new_name='staff',
        ),
    ]
