# Generated by Django 5.0.6 on 2024-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellationTitle', models.CharField(max_length=100)),
                ('cancellationNotification', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitmentTitle', models.CharField(max_length=200)),
                ('recruitmentNotification', models.FileField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNo', models.IntegerField()),
                ('advertisementNo', models.CharField(max_length=50)),
                ('nameOfPost', models.CharField(max_length=100)),
                ('dateExtension', models.CharField(blank=True, max_length=150, null=True)),
                ('applicationForm', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisementNo', models.CharField(max_length=50)),
                ('resultDescription', models.CharField(blank=True, max_length=150, null=True)),
                ('result', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfPost', models.CharField(max_length=100)),
                ('status1', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('status2', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
    ]
