# Generated by Django 4.2.15 on 2024-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_links',
            name='area',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
