# Generated by Django 4.2.15 on 2024-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sections', '0002_related_links_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Corporate film about NIWE', max_length=200)),
                ('video_url', models.URLField()),
                ('hindi_version_url', models.URLField()),
            ],
        ),
    ]
