# Generated by Django 5.0.6 on 2024-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Section', '0002_certificationandinformationtechnologystaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandinformationtechnologystaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='financeandadministrationstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='offshorewinddevelopstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchanddevelopmentstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='skilldevelopmentandtrainingstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='testingstandardsandregulationstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
        migrations.AlterField(
            model_name='windresourceassessmentstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Avaliable', max_length=50),
        ),
    ]
