# Generated by Django 5.0.6 on 2024-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Section', '0005_directorgeneralofficestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneralofficestaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
