# Generated by Django 4.2.15 on 2024-09-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Section', '0009_certificationstaffphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificationStaffPhoto',
        ),
    ]
