# Generated by Django 5.0.6 on 2024-06-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0003_rename_faqs_faqs_faq_faqs_preambel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='preambel',
            new_name='preamble',
        ),
    ]
