# Generated by Django 4.2.15 on 2024-08-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0006_dataentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntry',
            new_name='WEG_Installation_Details_India',
        ),
    ]
