# Generated by Django 4.2.15 on 2024-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0007_rename_dataentry_weg_installation_details_india'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2002_03',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2003_04',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2004_05',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2005_06',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2006_07',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2007_08',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2008_09',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2009_10',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2010_11',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2011_12',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2012_13',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2013_14',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2014_15',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2015_16',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2016_17',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2017_18',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2018_19',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2019_20',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2020_21',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='_2021_22',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weg_installation_details_india',
            name='upto_31_03_2002',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
