# Generated by Django 4.2.15 on 2024-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0008_alter_weg_installation_details_india__2002_03_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weg_installation_details_india',
            old_name='_2002_03',
            new_name='y_2002_03',
        ),
    ]
