# Generated by Django 4.2.15 on 2024-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0010_rename__2003_04_weg_installation_details_india_year_2002_03_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weg_install_world_wise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
