# Generated by Django 4.2.15 on 2024-09-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0013_newsletters_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
