# Generated by Django 4.2.15 on 2024-09-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0016_alter_newsletters_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletters',
            name='File',
        ),
    ]
