# Generated by Django 4.2.15 on 2024-09-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0017_remove_newsletters_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
