# Generated by Django 4.2.15 on 2024-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0019_newsletters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
