# Generated by Django 4.2.15 on 2024-09-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0022_alter_newsletters_docs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualReport',
        ),
    ]
