# Generated by Django 4.2.15 on 2024-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0024_annualreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
