# Generated by Django 4.2.15 on 2024-09-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0026_internationaltraining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalTraining',
        ),
    ]
