# Generated by Django 4.2.15 on 2024-09-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0028_sdt_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SDT_Library',
        ),
    ]
