# Generated by Django 4.2.15 on 2024-10-07 07:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Section', '0029_delete_sdt_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
