# Generated by Django 5.0.6 on 2024-06-20 06:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0003_image_wra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_and_Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('NIWE_Pan_ARN_GST_Details', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Offshore_Wind_Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='Not Necessary', null=True),
        ),
        migrations.AlterField(
            model_name='wind_resources_assessment',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('OWD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Depart_Section.offshore_wind_development')),
            ],
        ),
    ]
