# Generated by Django 5.0.6 on 2024-08-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0004_finance_and_administration_offshore_wind_development_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
