# Generated by Django 5.0.6 on 2024-08-21 08:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0005_remove_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_developements_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
