# Generated by Django 5.0.6 on 2024-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0006_skill_developements_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_developements_training',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wind_resources_assessment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
