# Generated by Django 4.2.15 on 2024-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0009_wind_terbine_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='depart_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('Version', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Download', models.FileField(upload_to='departs/')),
            ],
        ),
    ]
