# Generated by Django 4.2.15 on 2024-09-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0013_rename_agreement_date_department_testing_measuretype_agreement_signed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department_testing_measureType',
        ),
    ]
