# Generated by Django 4.2.15 on 2024-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0017_sdt_workshop_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_vayumitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='annual-reports/')),
            ],
        ),
    ]
