# Generated by Django 4.2.15 on 2024-09-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0018_sdt_vayumitra'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='annual-reports/')),
                ('docs', models.FileField(upload_to='annual-reports/')),
            ],
        ),
    ]
