# Generated by Django 4.2.15 on 2024-09-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0023_rename_year_sdt_internationaltraining_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdt_internationaltraining',
            old_name='docs',
            new_name='url',
        ),
    ]
