# Generated by Django 4.2.15 on 2024-09-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0027_sdt_globalwindday_sdt_webinar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customize_Training',
            new_name='SDT_Customize_Training',
        ),
    ]
