# Generated by Django 4.2.15 on 2024-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0028_rename_customize_training_sdt_customize_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_webinar',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='sdt_webinar',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sdt_webinar',
            name='url',
        ),
        migrations.AddField(
            model_name='sdt_webinar',
            name='docs',
            field=models.FileField(default=1, upload_to='annual-reports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sdt_webinar',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
