# Generated by Django 4.2.15 on 2024-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0029_remove_sdt_webinar_serial_remove_sdt_webinar_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_webinar',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
