# Generated by Django 4.2.15 on 2024-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0031_sdt_short_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRA_Sale_publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('product', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WRA_srra_stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('state_ut', models.CharField(max_length=250)),
                ('phase1', models.CharField(max_length=250)),
                ('phase2', models.CharField(max_length=250)),
                ('ams', models.CharField(max_length=250)),
                ('meda', models.CharField(max_length=250)),
                ('anert', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
            ],
        ),
    ]
