# Generated by Django 4.2.15 on 2024-09-23 11:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0043_alter_sdt_national_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_national',
            name='page',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdt_national',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
