# Generated by Django 4.2.15 on 2024-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0045_remove_sdt_national_page_sdt_national_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_national',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
