# Generated by Django 4.2.15 on 2024-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0046_alter_sdt_national_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_national_page',
            name='data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
