# Generated by Django 4.2.15 on 2024-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0048_alter_sdt_national_page_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_national',
            name='url',
        ),
        migrations.AddField(
            model_name='sdt_national_page',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
