# Generated by Django 4.2.15 on 2024-09-24 05:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0049_remove_sdt_national_url_sdt_national_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDT_InternationalTraining_eitec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_internationaltraining')),
            ],
        ),
        migrations.CreateModel(
            name='SDT_InternationalTraining_sub_eitec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', tinymce.models.HTMLField(blank=True, null=True)),
                ('eitec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_internationaltraining_eitec')),
            ],
        ),
    ]
