# Generated by Django 4.2.15 on 2024-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0062_sdt_training_calender_sdt_training_sub_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_training_calender',
            name='training_type',
            field=models.CharField(default='Default Training Type', max_length=100),
        ),
    ]
