# Generated by Django 5.0.6 on 2024-09-26 11:33

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0067_alter_wra_sale_publication_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_globalwindday',
            name='url',
        ),
        migrations.CreateModel(
            name='SDT_Global_Sub_Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_globalwindday')),
            ],
        ),
    ]
