# Generated by Django 4.2.15 on 2024-09-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0069_department_fna_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Fna_Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('docs', models.FileField(upload_to='departs/')),
            ],
        ),
    ]
