# Generated by Django 4.2.15 on 2024-09-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0070_department_fna_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_vayumitra',
            name='docs',
        ),
        migrations.CreateModel(
            name='SDT_Vayumitra_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='annual-reports/')),
                ('url', models.URLField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depart_Section.sdt_vayumitra')),
            ],
        ),
    ]
