# Generated by Django 4.2.15 on 2024-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0072_sdt_vayumitra_docs_sdt_vayumitra_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_vayumitra',
            name='title_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
