# Generated by Django 4.2.15 on 2024-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0074_alter_sdt_vayumitra_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='title_type',
            field=models.CharField(blank=True, default='docs', max_length=20),
        ),
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
