# Generated by Django 5.0.6 on 2024-09-27 11:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0077_alter_wra_sale_publication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='remarks',
            field=tinymce.models.HTMLField(),
        ),
    ]
