# Generated by Django 5.0.6 on 2024-09-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0078_alter_wra_sale_publication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wra_sale_publication',
            name='remarks',
            field=models.CharField(max_length=275),
        ),
    ]
