# Generated by Django 4.2.15 on 2024-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0083_sdt_ireda_news_sdt_ireda_sub_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_vayumitra',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdt_vayumitra',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='annual-reports/'),
        ),
    ]
