# Generated by Django 4.2.15 on 2024-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0084_sdt_vayumitra_url_alter_sdt_vayumitra_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdt_vayumitra',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
