# Generated by Django 4.2.15 on 2024-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0087_remove_sdt_workshop_url_sdt_workshop_type_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdt_workshop_type',
            name='title',
        ),
        migrations.AddField(
            model_name='sdt_workshop',
            name='subTitle',
            field=models.CharField(default='sub-title', max_length=255),
        ),
    ]
