# Generated by Django 4.2.15 on 2024-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depart_Section', '0088_remove_sdt_workshop_type_title_sdt_workshop_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdt_workshop',
            name='subTitle',
            field=models.CharField(max_length=255),
        ),
    ]
