# Generated by Django 5.0.6 on 2024-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0004_rename_mission_charter_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_general_message',
            name='Dirs_image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
