# Generated by Django 4.2.15 on 2024-10-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Right_To_Information', '0003_information_remove_righttoinformation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
